### PR TITLE
+ palabras y tildes, también correcciones

### PR DESCRIPTION
**Pull request by Rudxain**

### CODE REVIEW

**Comment by UltiRequiem** [comment]
thanks!

**Comment by Rudxain** [comment]
@UltiRequiem You're welcome! but I forgot to add a comma at line 106 (I noticed thanks to CI). I'm sorry for the oversight

**Comment by UltiRequiem** [comment]
> @UltiRequiem You're welcome! but I forgot to add a comma at line 106 (I noticed thanks to CI). I'm sorry for the oversight

Would be nice if you fix it bro

**Comment by Rudxain** [comment]
ok I'll open another PR, lol

**Pull request merged**
